[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 300

[nixpacks]
python-version = "3.11"

[[services.ports]]
handlers = ["http"]
port = "80"

[[services.ports]]
handlers = ["tls"]
port = "443"
